/**
* This script was generated by the Schema Diff utility in Supabase.
*/

create table if not exists public.profiles (
    id uuid not null,
    "email" text not null,
    constraint profiles_pkey primary key (id),
    constraint profiles_id_fkey foreign key (id) references auth.users (id) on delete cascade
) tablespace pg_default;

-- Create a trigger function to automatically insert a new profile when a new user signs up
create or replace function public.handle_new_user() returns trigger as $$
begin
  insert into public.profiles (id, email) values (new.id, new.email);
  return new;
end;
$$ language plpgsql security definer;

-- Create a trigger to call the function when a new user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Enable RLS on the profiles table
alter table public.profiles enable row level security;

-- Allow users to view their own profile
create policy "Users can view their own profile." on public.profiles
  for select using (auth.uid() = id);

-- Allow users to update their own profile
create policy "Users can update their own profile." on public.profiles
  for update using (auth.uid() = id);

-- Enable RLS on the feedback table
alter table public.feedback enable row level security;

-- Allow users to insert feedback
create policy "Users can insert feedback." on public.feedback
  for insert with check (auth.role() = 'authenticated');

-- Allow users to view their own feedback
alter table public.feedback add column if not exists user_id uuid references auth.users(id);
create policy "Users can view their own feedback." on public.feedback
  for select using (auth.uid() = user_id);
